#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

###############################################################################
# enable scim for chewing in VNC
###############################################################################
export XXMODIFIERS=@im=SCIM
export GTK_IM_MODULE="scim"
XIM="SCIM"
XIM_PROGRAM=scim
XIM_ARGS="-d"
###############################################################################

# exec /etc/X11/xinit/xinitrc[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
mate-session &
mate-terminal &
# cinnamon-session &
# xfce-session &
# gnome-session &
# lxsession &
